### ISSUE TITLE
Сохранять в чеке информацию о торговой точке

### ISSUE THREAD

**Issue by vladimirshefer** [receipt-project/receipt-java#51]
Нужно сохранять из FnsReceiptDto в Receipt следующие поля:
retailPlaceAddress - адрес торговой точки
userInn - инн торговой точки
user - название торговой точки

И так же отдавать их на фронт при создании и запросе чеков

**Comment by yasnovmi** [comment]
все поля nullable?

**Comment by yasnovmi** [comment]
Может будем userInn и user которые приходят от фнс называть retailInn и retail?
